---
name: "CI"

on:
  - "push"

jobs:
  build-mac:
    runs-on: 
      - "macos-latest"
    steps:
      - 
        uses: "actions/checkout@v4"
      -
        name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: "go/go.mod"
          cache-dependency-path: "go/go.sum"
      -
        name: "Build"
        run: "go build -C go -o ../ca.michaelabon.logitechlitra.sdPlugin ."
